yolo_detector:
  ros__parameters:
    image_topic: /camera/color/image_raw
    objects_topic: /detector/objects
    debug_image_topic: /detector/debug_image
    backend: yoloe
    model_path: /home/unitree/MscapeTech/models/yoloe-11s-seg.pt
    model_kind: yoloe
    prompts: 'red button,green button,black knob,selector switch,rotary switch,toggle switch,control panel switch,cabinet door handle,indicator light,pilot light'
    prompt_free: false
    best_handle_only: false
    conf_thres: 0.08
    iou_thres: 0.45
    imgsz: 640
    device: ''
    publish_debug_image: true

coordinate_projector:
  ros__parameters:
    objects_topic: /detector/objects
    depth_topic: /camera/aligned_depth_to_color/image_raw
    camera_info_topic: /camera/color/camera_info
    objects_3d_topic: /detector/objects_3d
    target_point_topic: /detector/target_point
    target_pose_topic: /detector/target_pose
    target_joint_state_topic: /detector/target_joint_state
    target_frame: ''
    handeye_mode: eye-in-hand
    handeye_npy_path: /home/unitree/MscapeTech/Hand_Eye_Calib/outputs/eye_in_hand_20260630_150210.json
    handeye_target_frame: torso_link
    robot_model: h2
    workspace_root: /home/unitree/MscapeTech
    urdf_path: /home/unitree/MscapeTech/unitree_ros/robots/h2_description/H2.urdf
    base_link: torso_link
    hand_link: right_wrist_yaw_link
    camera_link: ''
    network_interface: eth0
    domain_id: 0
    joint_json_path: ''
    lock_waist: true
    h2_ee_offset_xyz: [0.05, 0.0, 0.0]
    class_filter: ''
    min_confidence: 0.25
    depth_radius: 3
    depth_scale: 0.001
    min_depth_m: 0.10
    max_depth_m: 5.0
    publish_invalid: false
    publish_target_pose: true
    target_pose_orientation_xyzw: [0.0, 0.0, 0.0, 1.0]
    publish_target_joint_state: true
    publish_failed_ik_solution: false
    ik_target_link: right_wrist_yaw_link
    ik_active_joints: 'right_shoulder_pitch_joint,right_shoulder_roll_joint,right_shoulder_yaw_joint,right_elbow_joint,right_wrist_roll_joint,right_wrist_pitch_joint,right_wrist_yaw_joint'
    ik_end_effector_offset_xyz: [0.05, 0.0, 0.0]
    ik_target_position_offset_xyz: [0.0, 0.0, 0.0]
    ik_max_iterations: 120
    ik_tolerance_position: 0.005
    ik_tolerance_orientation: 3.2
    ik_damping: 0.001
    ik_step_scale: 0.4
    ik_position_weight: 1.0
    ik_orientation_weight: 0.0
    stale_depth_sec: 0.5
    transform_timeout_sec: 0.05

web_dashboard:
  ros__parameters:
    web_host: '0.0.0.0'
    web_port: 8080
    jpeg_quality: 80
    frame_timeout_sec: 2.0
    debug_image_topic: /detector/debug_image
    objects_topic: /detector/objects
    objects_3d_topic: /detector/objects_3d
    target_point_topic: /detector/target_point
    target_pose_topic: /detector/target_pose
    target_joint_state_topic: /detector/target_joint_state
